### ISSUE TITLE
Aw Snap! with every Video

### ISSUE THREAD

**Issue by darksylinc** [saiarcot895/chromium-ubuntu-build#82]
Hi!

In latest Version 83.0.4103.44 (Developer Build) Ubuntu 18.04 (64-bit)
I started getting "Aw Snap!" when trying to play any video. It was working fine before the update.

Information:

Xubuntu 18.04 (64-bit)
Kernel 5.3.0-51-generic
Affected GPUs (2 different systems):
 * Desktop: Radeon RX 560 Series (POLARIS11, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0) (0x67ff),  Mesa 20.0.0-devel (git-d55573aac6)
 * Laptop: Radeon Vega 8 (AMD Ryzen 5 2500U). I don't have the mesa build info here right now with me

It's not of much use without symbols, but stacktrace is:

```
[21772:21772:0518/201533.071147:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!

Received signal 11 SEGV_MAPERR 000000000000
#0 0x55997bc62f99 (/usr/lib/chromium-browser/chromium-browser+0x3f0bf98)
#1 0x55997bbc2de3 (/usr/lib/chromium-browser/chromium-browser+0x3e6bde2)
#2 0x55997bc62b21 (/usr/lib/chromium-browser/chromium-browser+0x3f0bb20)
#3 0x7fc9acd4f890 (/lib/x86_64-linux-gnu/libpthread-2.27.so+0x1288f)
#4 0x7fc9a61595a1 (/lib/x86_64-linux-gnu/libc-2.27.so+0x18e5a0)
#5 0x55997bc5266e (/usr/lib/chromium-browser/chromium-browser+0x3efb66d)
#6 0x55997952e138 (/usr/lib/chromium-browser/chromium-browser+0x17d7137)
#7 0x55997952e0d2 (/usr/lib/chromium-browser/chromium-browser+0x17d70d1)
#8 0x5599795ad49a (/usr/lib/chromium-browser/chromium-browser+0x1856499)
#9 0x5599795a6ddd (/usr/lib/chromium-browser/chromium-browser+0x184fddc)
#10 0x55997959c427 (/usr/lib/chromium-browser/chromium-browser+0x1845426)
#11 0x55997959c0e7 (/usr/lib/chromium-browser/chromium-browser+0x18450e6)
#12 0x55997959e066 (/usr/lib/chromium-browser/chromium-browser+0x1847065)
#13 0x55997959df17 (/usr/lib/chromium-browser/chromium-browser+0x1846f16)
#14 0x5599795f9d68 (/usr/lib/chromium-browser/chromium-browser+0x18a2d67)
#15 0x5599795f6759 (/usr/lib/chromium-browser/chromium-browser+0x189f758)
#16 0x559979517051 (/usr/lib/chromium-browser/chromium-browser+0x17c0050)
#17 0x55997bc1481f (/usr/lib/chromium-browser/chromium-browser+0x3ebd81e)
#18 0x55997bc24f16 (/usr/lib/chromium-browser/chromium-browser+0x3ecdf15)
#19 0x55997bc24cd6 (/usr/lib/chromium-browser/chromium-browser+0x3ecdcd5)
#20 0x55997bbd6b0a (/usr/lib/chromium-browser/chromium-browser+0x3e7fb09)
#21 0x55997bc25485 (/usr/lib/chromium-browser/chromium-browser+0x3ece484)
#22 0x55997bbfa608 (/usr/lib/chromium-browser/chromium-browser+0x3ea3607)
#23 0x55997bc311c2 (/usr/lib/chromium-browser/chromium-browser+0x3eda1c1)
#24 0x55997bc7361d (/usr/lib/chromium-browser/chromium-browser+0x3f1c61c)
#25 0x7fc9acd446db start_thread
#26 0x7fc9a60ec88f clone
  r8: 00007fc9626f61b8  r9: 0000000000000000 r10: 00007fc9580008d0 r11: 0000000000000000
 r12: 00007fc95800c0c0 r13: 0000000000000108 r14: 0000000000000000 r15: 00007fc9626f6070
  di: 0000000000000000  si: 0000000000000000  bp: 00007fc9626f6060  bx: 00007fc9626f61b8
  dx: 0000000000000000  ax: be58ff2d680f6800  cx: 0000000000000000  sp: 00007fc9626f6018
  ip: 00007fc9a61595a1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
```

Note that these:

```
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
```

happen at init (i.e. long before any crash). I don't know if these errors messages were present before.

Testing the same version without VAAPI patches (fetched using [bisect-builds.py](https://www.chromium.org/developers/bisect-builds-py)) shows no crash.

**Comment by saiarcot895** [comment]
Can you do me a favor and run the following steps:

1.  Run Chromium from the terminal with the `--disable-in-process-stack-traces` flag. This should cause Chromium to let the OS collect a core file.
2. Try to play a video.
3. Look for a `.crash` file in `/var/crash/`. Upload the crash file here. (Note that it may potentially contain some personal info, such as hostname or username.)

**Comment by darksylinc** [comment]
[_usr_lib_chromium-browser_chromium-browser.1000.crash.zip](https://github.com/saiarcot895/chromium-ubuntu-build/files/4647937/_usr_lib_chromium-browser_chromium-browser.1000.crash.zip)

**Comment by thodt** [comment]
Same problem on different pc:
1. Ryzen 7 3700X + Nvidia 1660 Super
2. Core i7-7800X + Radeon HD 7790
3. Asus Zenbook UX331UA, Core i7 + HD620 integrated graphics.

**Comment by Ertego** [comment]
Can also confirm this on a Microsoft Surface Pro 3 with an Intel i3

**Comment by hairyasian** [comment]
> Can you do me a favor and run the following steps:
> 
> 1. Run Chromium from the terminal with the `--disable-in-process-stack-traces` flag. This should cause Chromium to let the OS collect a core file.
> 2. Try to play a video.
> 3. Look for a `.crash` file in `/var/crash/`. Upload the crash file here. (Note that it may potentially contain some personal info, such as hostname or username.)

thx to the author for submitting this report. been meaning to myself...

and to the owner, here's my dump:

https://gist.github.com/hairyasian/a22be6301dbdaedb23fa010d62738b17

thx let me know if anything else might help...

**Comment by helijia21** [comment]
same issue with vainfo shows that the drivers has already loaded with out any proble
Playback video files by mpv with vaapi and its work fine.
But chromium (dev or beta) crash on every page with video

**Comment by saiarcot895** [comment]
With the number of users reporting this, it's likely a common problem, and unfortunately, I didn't compile full debug symbols into Chromium. From what I can figure out, it's crashing in `strlen` while getting called from some media functions.

I'm working on making a package with more debug information and then trying to get a core dump from that.

**Comment by darksylinc** [comment]
I wish I could help by debugging the program, but I find the instructions on how to build this repo quite confusing.

If you have a script I can run that just works to build patched chromium, I could take a look.

**Comment by saiarcot895** [comment]
I'm still working on getting that build done.

**Comment by saiarcot895** [comment]
I got a debug build done, got a backtrace, and I think I know what happened.

Backtrace:

```
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x000055d4eb2de4fe in std::__1::char_traits<char>::length (__s=0x0) at ../../buildtools/third_party/libc++/trunk/include/__string:217
#2  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<decltype(nullptr)>(char const*) (this=<optimized out>, __s=0x0) at ../../buildtools/third_party/libc++/trunk/include/string:819
#3  base::Value::Value (this=0x7f1470c79080, in_string=0x0) at ../../base/values.cc:218
#4  0x000055d4e8b95a26 in media::internal::MediaSerializer<char const*>::Serialize (value=0x0) at ../../media/base/media_serializers_base.h:22
#5  media::MediaSerialize<char const*> (t=<optimized out>) at ../../media/base/media_serializers_base.h:29
#6  media::internal::MediaSerializer<base::Location>::Serialize (value=...) at ../../media/base/media_serializers.h:381
#7  media::MediaSerialize<base::Location> (t=...) at ../../media/base/media_serializers_base.h:29
#8  media::Status::AddFrame (this=<optimized out>, location=...) at ../../media/base/status.cc:69
#9  0x000055d4e8b959c1 in media::Status::Status (this=0x7f1470c79178, code=media::StatusCode::kDecoderMissingCdmForEncryptedContent, message=..., location=...) at ../../media/base/status.cc:19
#10 0x000055d4e8c1b985 in media::DecryptingVideoDecoder::Initialize(media::VideoDecoderConfig const&, bool, media::CdmContext*, base::OnceCallback<void (media::Status)>, base::RepeatingCallback<void (scoped_refptr<media::VideoFrame>)> const&, base::RepeatingCallback<void (media::WaitingReason)> const&) (this=<optimized out>, config=..., cdm_context=0x0, init_cb=..., output_cb=..., waiting_cb=...) at ../../media/filters/decrypting_video_decoder.cc:58
#11 0x000055d4e8c1563a in media::DecoderStreamTraits<(media::DemuxerStream::Type)2>::InitializeDecoder(media::VideoDecoder*, media::VideoDecoderConfig const&, bool, media::CdmContext*, base::OnceCallback<void (media::Status)>, base::RepeatingCallback<void (scoped_refptr<media::VideoFrame>)> const&, base::RepeatingCallback<void (media::WaitingReason)> const&) (this=<optimized out>, decoder=0x7f145c014080, config=..., low_delay=<optimized out>, cdm_context=0x0, init_cb=..., output_cb=..., waiting_cb=...) at ../../media/filters/decoder_stream_traits.cc:186
#12 0x000055d4e8c0b0c3 in media::DecoderSelector<(media::DemuxerStream::Type)2>::InitializeDecoder (this=<optimized out>) at ../../media/filters/decoder_selector.cc:154
#13 0x000055d4e8c0ad72 in media::DecoderSelector<(media::DemuxerStream::Type)2>::SelectDecoder(base::OnceCallback<void (std::__1::unique_ptr<media::VideoDecoder, std::__1::default_delete<media::VideoDecoder> >, std::__1::unique_ptr<media::DecryptingDemuxerStream, std::__1::default_delete<media::DecryptingDemuxerStream> >)>, base::RepeatingCallback<void (scoped_refptr<media::VideoFrame>)>) (this=0x7f145c013e28, select_decoder_cb=..., output_cb=...) at ../../media/filters/decoder_selector.cc:91
#14 0x000055d4e8c0ce36 in media::DecoderStream<(media::DemuxerStream::Type)2>::SelectDecoder (this=<optimized out>) at ../../media/filters/decoder_stream.cc:324
#15 0x000055d4e8c0cce7 in media::DecoderStream<(media::DemuxerStream::Type)2>::Initialize(media::DemuxerStream*, base::OnceCallback<void (bool)>, media::CdmContext*, base::RepeatingCallback<void (media::PipelineStatistics const&)>, base::RepeatingCallback<void (media::WaitingReason)>) (this=0x7f145c013db0, stream=0x55d4f35f4830, init_cb=..., cdm_context=0x0, statistics_cb=..., waiting_cb=...) at ../../media/filters/decoder_stream.cc:175
#16 0x000055d4e8c61041 in media::VideoRendererImpl::Initialize(media::DemuxerStream*, media::CdmContext*, media::RendererClient*, base::RepeatingCallback<bool (std::__1::vector<base::TimeDelta, std::__1::allocator<base::TimeDelta> > const&, std::__1::vector<base::TimeTicks, std::__1::allocator<base::TimeTicks> >*)> const&, base::OnceCallback<void (media::PipelineStatus)>) (this=<optimized out>, stream=<optimized out>, cdm_context=0x0, client=0x55d4f35f4830, wall_clock_time_cb=..., init_cb=...) at ../../media/renderers/video_renderer_impl.cc:208
#17 0x000055d4e8c5db51 in media::RendererImpl::InitializeVideoRenderer (this=0x55d4f34517e0) at ../../media/renderers/renderer_impl.cc:448
#18 0x000055d4e8b7fd41 in base::OnceCallback<void (media::PipelineStatus)>::Run(media::PipelineStatus) && (this=<optimized out>, args=media::PIPELINE_OK) at ../../base/callback.h:99
#19 base::internal::FunctorTraits<base::OnceCallback<void (media::PipelineStatus)>, void>::Invoke<base::OnceCallback<void (media::PipelineStatus)>, media::PipelineStatus>(base::OnceCallback<void (media::PipelineStatus)>&&, media::PipelineStatus&&) (callback=..., args=<optimized out>) at ../../base/bind_internal.h:596
#20 base::internal::InvokeHelper<false, void>::MakeItSo<base::OnceCallback<void (media::PipelineStatus)>, media::PipelineStatus>(base::OnceCallback<void (media::PipelineStatus)>&&, media::PipelineStatus&&) (functor=..., args=<optimized out>) at ../../base/bind_internal.h:636
#21 base::internal::Invoker<base::internal::BindState<base::OnceCallback<void (media::PipelineStatus)>, media::PipelineStatus>, void ()>::RunImpl<base::OnceCallback<void (media::PipelineStatus)>, std::__1::tuple<media::PipelineStatus>, 0ul>(base::OnceCallback<void (media::PipelineStatus)>&&, std::__1::tuple<media::PipelineStatus>&&, std::__1::integer_sequence<unsigned long, 0ul>) (functor=..., bound=...) at ../../base/bind_internal.h:709
#22 base::internal::Invoker<base::internal::BindState<base::OnceCallback<void (media::PipelineStatus)>, media::PipelineStatus>, void ()>::RunOnce(base::internal::BindStateBase*) (base=<optimized out>) at ../../base/bind_internal.h:678
#23 0x000055d4eb2a368f in base::OnceCallback<void ()>::Run() && (this=<optimized out>) at ../../base/callback.h:99
#24 base::TaskAnnotator::RunTask (this=<optimized out>, trace_event_name=0x55d4f016ff20 "SequenceManager RunTask", pending_task=0x7f145c001de0) at ../../base/task/common/task_annotator.cc:142
#25 0x000055d4eb2b315b in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl (this=0x55d4f3451650, continuation_lazy_now=0x7f1470c79940) at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:329
#26 0x000055d4eb2b2f2f in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork (this=0x55d4f3451650) at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:254
#27 0x000055d4eb26749a in base::MessagePumpDefault::Run (this=0x7f145c001ba0, delegate=0x55d4f3451658) at ../../base/message_loop/message_pump_default.cc:39
#28 0x000055d4eb2b36b5 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (this=0x55d4f3451650, application_tasks_allowed=<optimized out>, timeout=...) at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:443
#29 0x000055d4eb28a570 in base::RunLoop::Run (this=0x7f1470c79aa0) at ../../base/run_loop.cc:124
#30 0x000055d4eb2c0ddf in base::Thread::ThreadMain (this=0x55d4f34a9e10) at ../../base/threading/thread.cc:380
#31 0x000055d4eb2fc0ae in base::(anonymous namespace)::ThreadFunc (params=0x55d4f31fe200) at ../../base/threading/platform_thread_posix.cc:81
#32 0x00007f14bd83d6db in start_thread (arg=0x7f1470c7a700) at pthread_create.c:463
#33 0x00007f14b6be688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

What's happening is that there's code in the media decoding path that logs the function, file and line number of the source code whenever the status changes. The way it gets the function, file, and line number is by using compiler-builtin functions if available; otherwise, it defaults to `nullptr`/0. For clang, these compiler builtins are made available in Clang 9 and newer, but Bionic and Xenial compile with Clang 8. The code that serializes that info, however, doesn't check to see if the string is `nullptr`, and goes ahead to get the length of the string; this then causes a segfault.

The next build on the Dev and Beta branches should have a fix for this.
